test melpazoid on matrix of Emacs versions 2

diff --git a/.github/workflows/melpazoid-release.yml b/.github/workflows/melpazoid-release.yml
--- a/.github/workflows/melpazoid-release.yml
+++ b/.github/workflows/melpazoid-release.yml
@@ -9,6 +9,16 @@ name: melpazoid-release
 jobs:
   build:
     runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        emacs_version:
+          - 29.1
+          - 29.2
+          - 29.3
+          - 29.4
+          - 30.1
+          - release-snapshot
     steps:
       - name: Get repo to access in conteiner
         uses: actions/checkout@v5
@@ -18,10 +28,14 @@ jobs:
         uses: actions/setup-python@v5
         with:
           python-version: 3.12
+      - name: Install Emacs
+        uses: purcell/setup-emacs@master
+        with:
+          version: ${{ matrix.emacs_version }}
       - name: Install
         run: |
           python -m pip install --upgrade pip
-          sudo apt-get install emacs-nox  && emacs --version
+          # sudo apt-get install emacs-nox  && emacs --version
           git clone https://github.com/riscy/melpazoid.git ~/melpazoid
           pip install ~/melpazoid
       - name: Tests async
@@ -74,6 +88,9 @@ jobs:
           fi
           if grep -q ' with [melpazoid]' output.log ; then
             echo "Melpazoid warning detected, failing workflow" ; exit 1
+          fi
+          if grep -q ' with package-lint ' output.log ; then
+            echo "Checkdoc warning detected, failing workflow" ; exit 1
           fi
           if grep -q ' with checkdoc ' output.log ; then
             echo "Checkdoc warning detected, failing workflow" ; exit 1
diff --git a/.github/workflows/melpazoid.yml b/.github/workflows/melpazoid.yml
--- a/.github/workflows/melpazoid.yml
+++ b/.github/workflows/melpazoid.yml
@@ -9,14 +9,16 @@ name: melpazoid
 jobs:
   build:
     runs-on: ubuntu-latest
-    matrix:
-      emacs_version:
-        - 29.1
-        - 29.2
-        - 29.3
-        - 29.4
-        - 30.1
-        - release-snapshot
+    strategy:
+      fail-fast: true
+      matrix:
+        emacs_version:
+          - 29.1
+          - 29.2
+          - 29.3
+          - 29.4
+          - 30.1
+          - release-snapshot
     steps:
       - name: Get repo to access in conteiner
         uses: actions/checkout@v5
@@ -86,6 +88,9 @@ jobs:
           fi
           if grep -q ' with [melpazoid]' output.log ; then
             echo "Melpazoid warning detected, failing workflow" ; exit 1
+          fi
+          if grep -q ' with package-lint ' output.log ; then
+            echo "Checkdoc warning detected, failing workflow" ; exit 1
           fi
           if grep -q ' with checkdoc ' output.log ; then
             echo "Checkdoc warning detected, failing workflow" ; exit 1
