.dir-locals.el, better melpazoid

diff --git a/.github/workflows/melpazoid.yml b/.github/workflows/melpazoid.yml
--- a/.github/workflows/melpazoid.yml
+++ b/.github/workflows/melpazoid.yml
@@ -4,7 +4,7 @@
 # to .github/workflows/melpazoid.yml and modifying RECIPE and EXIST_OK below.
 ---
 name: melpazoid
-'on': [push, pull_request]
+'on': [push, pull_request, release]
 
 jobs:
   build:
@@ -71,6 +71,9 @@ jobs:
           fi
           if grep -q ': error: ' output.log ; then
             echo "Error detected, failing workflow" ; exit 1
+          fi
+          if grep -q ' with [melpazoid]' output.log ; then
+            echo "Melpazoid warning detected, failing workflow" ; exit 1
           fi
           if grep -q ' with checkdoc ' output.log ; then
             echo "Checkdoc warning detected, failing workflow" ; exit 1
